@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"admin"
}

### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Create the guest user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"guest",
    "password":"guest"
}

### Login the guest user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"guest",
    "password":"guest"
}

### Create the user with unmatched passwords
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"sdfsdf",
    "password":"12345",
    "password2":"1234"
}

### Create the user with password shorter than 4
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"sdfsdf",
    "password":"123",
    "password2":"123"
}

### Create the user with username containing special characters
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"sdfsdg@",
    "password":"1234",
    "password2":"1234"
}