@baseUrl = http://localhost:3000

### read all scores
GET {{baseUrl}}/scores

### add Jason's score
POST {{baseUrl}}/scores
Content-Type: application/json

{
  "nickname": "Jason",
  "score": 500
}

### add Jaques's score
POST {{baseUrl}}/scores
Content-Type: application/json

{
  "nickname": "Jaques",
  "score": 600
}