@baseUrl = http://localhost:3000

### read top 3 scores
GET {{baseUrl}}/scores?top=3


### add Jason's score
POST {{baseUrl}}/scores
Content-Type: application/json

{
  "nickname": "Jason",
  "score": 500
}

### read Jason's scores
GET {{baseUrl}}/scores/Jason

### add Jaques's score
POST {{baseUrl}}/scores
Content-Type: application/json

{
  "nickname": "Jaques",
  "score": 600
}